name: Publish TypeScript Package

on:
  workflow_call:
    inputs:
      workspace_directory:
        required: false
        type: string
        default: .
      working_directory:
        required: false
        type: string
        default: .
      pnpm_version:
        required: false
        type: string
        default: "9"

jobs:
  jsr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: ${{ inputs.pnpm_version }}
          run_install: |
            cwd: "${{ inputs.workspace_directory }}"
            recursive: true
      - run: pnpm -r build
        working-directory: ${{ inputs.working_directory }} 
      - name: choose version
        working-directory: ${{ inputs.working_directory }}
        run: |
          if [[ ! "$GITHUB_REF" =~ ^refs/tags/[0-9]+.[0-9]+.[0-9]+$ ]]; then
            timestamp=`date -u "+%Y%m%d%H%M%S%4N"`
            suffix="-dev.$timestamp+${{ github.sha }}"
            jq ".version = .version + \"$suffix\"" jsr.json > jsr.json.tmp
            mv jsr.json.tmp jsr.json
          fi
      - run: npx jsr publish --allow-dirty
        working-directory: ${{ inputs.working_directory }}
