name: Push Docker Image

on:
  workflow_call:
    inputs:
      working_directory:
        required: false
        type: string
        default: .
      repository:
        required: true
        type: string
      tag:
        required: false
        type: string
        default: git-${{ github.sha }}
    secrets:
      docker_username:
        required: true
      docker_access_token:
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
      - name: login
        run: docker login --username ${{ secrets.docker_username }} --password ${{ secrets.docker_access_token }}
      - name: build
        run: docker build -t planetariumhq/${{ inputs.repository }}:${{ inputs.tag }} .
        working-directory: ${{ inputs.working_directory }}
      - name: push (publish)
        run: docker push planetariumhq/${{ inputs.repository }}:${{ inputs.tag }}
